----------------------------------
--Prueba Tecnica de SQL
--Realizada por: Josue Bermudez
----------------------------------

USE master
GO

IF OBJECT_ID('tempdb.dbo.#CLIENTES', 'U') IS NOT NULL
  DROP TABLE #CLIENTES;

IF OBJECT_ID('tempdb.dbo.#VENTAS', 'U') IS NOT NULL
  DROP TABLE #VENTAS;

CREATE TABLE #CLIENTES(
	COD_CLIENTE int not null,
	NOM_CLIENTE nvarchar(50),
	CP_CLIENTE bigint NULL,
	LOC_CLIENTE nvarchar(50)
);

CREATE TABLE #VENTAS(
	COD_CLIENTE int not null,
	IMPORTE money
);


INSERT INTO #CLIENTES (COD_CLIENTE, NOM_CLIENTE, CP_CLIENTE, LOC_CLIENTE) VALUES(1, 'Construcciones ADA', 28001, 'Madrid')
INSERT INTO #CLIENTES (COD_CLIENTE, NOM_CLIENTE, CP_CLIENTE, LOC_CLIENTE) VALUES(2, 'Transportes Laborda', 41001, 'Sevilla')
INSERT INTO #CLIENTES (COD_CLIENTE, NOM_CLIENTE, CP_CLIENTE, LOC_CLIENTE) VALUES(3, 'Tintorería Rapida', 17001, 'Lugo')
INSERT INTO #CLIENTES (COD_CLIENTE, NOM_CLIENTE, CP_CLIENTE, LOC_CLIENTE) VALUES(4, 'Almacenes Grandes', 50001, 'Zaragoza')
INSERT INTO #CLIENTES (COD_CLIENTE, NOM_CLIENTE, CP_CLIENTE, LOC_CLIENTE) VALUES(5, 'Diario de Navarra', 26356, 'Barcelona')
INSERT INTO #CLIENTES (COD_CLIENTE, NOM_CLIENTE, CP_CLIENTE, LOC_CLIENTE) VALUES(6, 'Arión Grupo', 41562, 'Sevilla')
INSERT INTO #CLIENTES (COD_CLIENTE, NOM_CLIENTE, CP_CLIENTE, LOC_CLIENTE) VALUES(8, 'Banco de Finanzas', 28500, 'Madrid')
INSERT INTO #CLIENTES (COD_CLIENTE, NOM_CLIENTE, CP_CLIENTE, LOC_CLIENTE) VALUES(9, 'Seguros TRI', 41200, 'Madrid')
INSERT INTO #CLIENTES (COD_CLIENTE, NOM_CLIENTE, CP_CLIENTE, LOC_CLIENTE) VALUES(10, 'Mudanzas Bello', 15852, 'Barcelona')

INSERT INTO #VENTAS (COD_CLIENTE, IMPORTE) VALUES(4, 406.78)
INSERT INTO #VENTAS (COD_CLIENTE, IMPORTE) VALUES(5, 807.84)
INSERT INTO #VENTAS (COD_CLIENTE, IMPORTE) VALUES(6, 27.95)
INSERT INTO #VENTAS (COD_CLIENTE, IMPORTE) VALUES(8, 666.28)
INSERT INTO #VENTAS (COD_CLIENTE, IMPORTE) VALUES(9, 768.17)

--***(SENTENCIA 1)***
SELECT * 
FROM #CLIENTES 
ORDER BY NOM_CLIENTE


--***(SENTENCIA 2)***
SELECT * 
FROM #CLIENTES
WHERE LOC_CLIENTE = 'MAdrid'


--***(SENTENCIA 3)***
SELECT *
FROM #CLIENTES
WHERE CP_CLIENTE LIKE '41%'


--***(SENTENCIA 4)***
SELECT *
FROM #CLIENTES
WHERE (COD_CLIENTE < 10) OR NOM_CLIENTE LIKE 'A%'

--***(SENTENCIA 5)***
SELECT COUNT(*) as CLIENTESxLOCALIDAD, LOC_CLIENTE 
FROM #CLIENTES
GROUP BY LOC_CLIENTE


--***(SENTENCIA 6)***
DELETE 
FROM #CLIENTES
WHERE NOM_CLIENTE LIKE 'z%'
AND NOM_CLIENTE LIKE '%Z'


--***(SENTENCIA 7)***
UPDATE #CLIENTES
SET CP_CLIENTE = 28001
WHERE LOC_CLIENTE = 'Madrid'

SELECT * 
FROM #CLIENTES 


--***(SENTENCIA 8)***
SELECT a.*
FROM #CLIENTES a
INNER JOIN #VENTAS b ON a.COD_CLIENTE = b.COD_CLIENTE
WHERE b.IMPORTE <>0

 
--***(SENTENCIA 9)***
SELECT a.*,ISNULL( b.IMPORTE, 0) AS IMPORTE
FROM #CLIENTES a
LEFT JOIN #VENTAS b ON a.COD_CLIENTE = b.COD_CLIENTE


--***(SENTENCIA 10)***
UPDATE a
SET IMPORTE = 0
FROM #VENTAS a
INNER JOIN #CLIENTES b ON a.COD_CLIENTE = b.COD_CLIENTE
WHERE b.NOM_CLIENTE LIKE '%A%'

SELECT a.*,ISNULL( b.IMPORTE, 0) AS IMPORTE
FROM #CLIENTES a
LEFT JOIN #VENTAS b ON a.COD_CLIENTE = b.COD_CLIENTE


IF OBJECT_ID('tempdb.dbo.#CLIENTES', 'U') IS NOT NULL
  DROP TABLE #CLIENTES;

IF OBJECT_ID('tempdb.dbo.#VENTAS', 'U') IS NOT NULL
  DROP TABLE #VENTAS;


